modLoader="javafml"
loaderVersion="[2,)"
license="GNU LGPL 3.0"

[[mods]]
modId="naming_unconvention"
version="${mod_version}"
displayName="Naming Unconvention"
authors="QinomeD"
description='''
Random world name generator
'''

[[mixins]]
config="naming_unconvention.mixins.json"